[project]
name = "yad2-scraper-motorcycle-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "camoufox[geoip]>=0.4.11",
    "curl-cffi>=0.10.0",
    "python-dotenv>=1.1.0",
]
